# Base configs
baseurl: "https://photography.anthonycox.org"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Anthony Cox"
subtitle: "See the world through my eyes!"
author: "Anthony Cox"
header:
 title: "Photography"
 subtitle: "by Anthony Cox"
footer:
 name: "Hey there, my name is Anthony"
 bio: "Pharmacist and Academic"
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
